stages:
  - test
  - audit

test:
  stage: test
  image: babashka/babashka:latest
  script:
    - bb aur-test

self-audit:
  stage: audit
  image: babashka/babashka:latest
  script:
    - bb aur_audit.clj
